---
title: "Final_Project"
output: html_document
date: "2022-11-20"
---

# The Blue Zones: Why do people certain areas of the world live longer ? 

DELIVERABLES: 
###  1. A statement of the question or purpose. What problems or questions did you set out to analyse? What were the key issues raised? 


### 2. The background and preparation for conducting the project. How did you prepare for the project? What sources or background readings did you consult? What information did you use in developing your ideas from the conceptual stage to the finished project? 


### 3. Methodology. What did you do, and how did you do it? What statistical techniques did you use — for instance, scatterplots, correlation, confidence intervals, linear/logistic regression? 


### 4. Results and conclusions. This is where you summarise and present your data analyses and communicate your main results. What did you find out? This might include tables, graphs, or verbal summaries. What did you learn about the problem or question you set out to investigate? 


### 5. Discussion and critique. What did you learn about the process of carrying out your project? What went wrong, and how could you improve it next time? For instance, did any sources of bias creep into your survey or experiment? What advice would you give future students? 


contents:
1. Global map, life span distribution
2. Life expectancy: time series line plot; by country, continental
3. Multiple scatter plots: lifespan - other factors, plots of correlations

4. Run a model, talk about statistical indicators, no graphs needed

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(vroom)
library(ggThemeAssist)
library(rnaturalearth)
library(ggplot2)
library(rgdal)
library(httr)
library(rvest)
library(purrr)
library(dplyr)
library(ggplot2)
library(jsonlite)
library(lubridate)
library(stringr)
library(viridis)
library(leaflet)
library(leaflet.extras)
library(htmltools)
library(sf)
library(tidyverse)
library(lubridate)
library(ggmap)
library(ggrepel)
library(gridExtra)
library(pander)
library(here)
library(janitor)
library(skimr)
library(leaflet)
library(tmap)
library(tmaptools)
library(hrbrthemes)
library(mapview)
library(viridis)
```

