---
title: "data_vizualisations"
output: html_document
date: "2022-11-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(vroom)
library(tidyverse)
library(lubridate)
library(ggmap)
library(ggrepel)
library(gridExtra)
library(pander)
library(here)
library(sf)
library(janitor)
library(skimr)
library(leaflet)
library(tmap)
library(tmaptools)
library(hrbrthemes)
library(mapview)
library(viridis)
library(dplyr)
```

```{r}

life_exp =read.csv('data viz dataset/CLEANED-Life Expectancy - potential factors.csv')
health_nutrition=read.csv('data viz dataset/CLEANED-Health_Nutrition_and_Population 2.csv')

health_life_joined <- health_nutrition %>% 
  leftjoin(life_exp, by = c("country_name" = "Country" ))

health_life_joined <- merge(health_nutrition, life_exp, all.x = TRUE, by.x = c("country_name","year"), by.y = c("Country","Year"))

health_2014=health_life_joined%>%filter(year==2014)

health_2004=health_life_joined%>%filter(year==2004)

health_2000=health_life_joined%>%filter(year==2000)

```

```{r}
model1 <-lm(Life.expectancy~.,health_2014)

summary(model1)


#adjusting the linear model 

lm_new1=lm(Life.expectancy ~ Adult.Mortality + Total.expenditure + HIV.AIDS + Income.composition.of.resources,lc_2014)
  

summary(lm_new1)


```

