---
title: "Cleaning Data"
output: html_document
date: "2022-11-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Clean the data

```{r load library}
library(vroom)
library(tidyverse)
library(lubridate)
library(ggmap)
library(ggrepel)
library(gridExtra)
library(pander)
library(here)
library(sf)
library(janitor)
library(skimr)
library(leaflet)
library(tmap)
library(tmaptools)
library(hrbrthemes)
library(mapview)
library(viridis)
library(dplyr)
```


```{r Health_Nutrition_and_Population}

df1 <- read_csv(file = 'data viz dataset/Health_Nutrition_and_Population.csv', na = "..") 

# df1 <-df1[,-67]
# df1 <-df1[,-66]

df1 <- df1 %>% 
  pivot_longer(names_to = "year",
               values_to = "value",
               cols = -(1:4)) %>% 
  mutate(year = substr(year,1,4)) %>% 
  drop_na() %>% 
  janitor::clean_names() 

df1 <- df1 %>% 
  select("series_name", "country_name",	"country_code", "year", "value") %>% 
  pivot_wider(names_from = "series_name",
              values_from = "value") %>% 
  janitor::clean_names() 

    
glimpse(df1)

write.table(df1, file = "data viz dataset/CLEANED-Health_Nutrition_and_Population.csv", row.names = FALSE, na = "", sep = ",")
#storing the data in csv file, removing row name and column name

```


### read the infant immortality file and cleaning it
```{r infant-inmortality}


df1 <- read_csv(file = 'data viz dataset/(NEEDS CLEAN)-infant-inmortality.csv',skip=4) 
df1 <-df1[,-67]
df1 <-df1[,-66]

df1 <- df1 %>% 
  drop_na() %>% 
  pivot_longer(names_to = "year",
               values_to = "infant_inmortality",
               cols = -(1:4)) %>% 
  janitor::clean_names()


glimpse(df1)

write.table(df1, file = "data viz dataset/CLEANED-infant-mortality.csv", row.names = FALSE, na = "", sep = ",")
#storing the data in csv file, removing row name and column name



```


### read the life expectancy file and cleaning it

```{r life-expectancy}

#read in data, remove the first 3 rows
df2 <- read_csv(file = 'data viz dataset/(NEEDS CLEAN) life-expectancy-2020.csv',skip=4) 
df2 <-df2[,-67]
df2 <-df2[,-66]

df2 <- df2 %>% 
  drop_na() %>% 
  pivot_longer(names_to = "year",
               values_to = "life_expectancy",
               cols = -(1:4)) %>% 
  janitor::clean_names()


glimpse(df2)


write_csv(df2, file = "data viz dataset/CLEANED-life-expectancy-2020.csv", na = "")
#storing the data in csv file, removing row name and column name

```

##some graph

```{r some graph}

library(gapminder)
gapminder %>% ggplot(aes(x = continent, y=lifeExp, group_by = year, colour = continent))+
  facet_wrap(~year)+
  geom_boxplot()+
  labs(title = "Life Expectancy of Different Continents Over the Years")+
  theme_bw()+
  theme(legend.position = "None")

```


```{r cluster}

library(factoextra)

lifeExp_factors <- read_csv(file = "data viz dataset/CLEANED-Life Expectancy - potential factors.csv",show_col_types = FALSE) 

lifeExp_factors_cluster <- lifeExp_factors %>% 
  clean_names() %>% 
  filter(year==2014) %>% 
  select("life_expectancy", "gdp") %>% 
  na.omit()

# lifeExp_factors %>% 
#   clean_names() %>% 
#   filter(year==2014) %>% 
#   select("country", "life_expectancy", "gdp") %>% 
#   slice_max(gdp, n=10) %>% 
#   arrange(desc(gdp))
# 
# lifeExp_factors %>% 
#   clean_names() %>% 
#   filter(year==2014) %>% 
#   select("country", "life_expectancy", "gdp") %>% 
#   slice_max(life_expectancy, n=10) %>% 
#   arrange(desc(life_expectancy))

model_kmeans <- eclust(lifeExp_factors_cluster, "kmeans", k=3, graph = TRUE)

#Let's check the components of this object.
summary(model_kmeans)


library(ggpubr)

lifeExp_factors_withClusters<-mutate(lifeExp_factors_cluster, cluster = as.factor(model_kmeans$cluster))

ggplot(lifeExp_factors_withClusters, aes(x = gdp, y = life_expectancy, color =  as.factor(cluster))) +
  geom_jitter()+
  labs(color = "Cluster",
       title = "Clustering Countries by GDP and Life Expectancy")

```

